version: '3'

networks:
 prodnetwork:
    driver: bridge

volumes:
  oracle_data:
    driver: local


services:
 oracle-11g:
  hostname: oracle
  image: ambientdocker/docker-oracle-xe-11g 
  ports:
    - "11521:1521"
    - "2222:22"
    - "18090:8080"
  networks:
    - prodnetwork
  volumes:
    - oracle_data:/u01

 postgresql-11:
  hostname: postgresql
  build: ./postgresql-11
  ports:
    - "15432:5432"
  environment:
    POSTGRES_PASSWORD: password
  networks:
    - prodnetwork


 phppgadmin:
  hostname: phppgadmin
  build: ./phpPgAdmin
  links:
    - postgresql-11:pg
  depends_on:
    - postgresql-11
  ports:
    - "29000:80"
  environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: password
  networks:
    - prodnetwork